language: node_js
node_js:
  - "node"
  - "lts/*"

services:
  - mongodb

cache:
  directories:
    - "front-end/node_modules"
    - "back-end/node_modules"

install:
  - cd front-end && npm install && cd ..
  - cd back-end && npm install && cd ..

script:
  - cd front-end && npm run test:unit && cd ..
  - cd back-end && npm test && cd ..
